### PR TITLE
GNOME 46 Support

### LINKED ISSUE #3: Update to GNOME 46
GNOME 46 has been released and required some minor changes to `add_actor`.

### PR DESCRIPTION
**Pull request by sungsphinx**
Fixes #3, only had to change a few things :D.

https://gjs.guide/extensions/upgrading/gnome-shell-46.html

Also changed the version inside metadata to `3`, as the current version is `2` not `999`, so the next release (if any) would probably be `3`.

### CODE REVIEW

**Comment by prurigro** [comment]
If you're displaying icons they're squished right up against the text. You can resolve by creating `stylesheet.css` and adding:

```css
.app-menu-icon {
    margin-right: 8px;
}
```

**Comment by fthx** [comment]
Hi all, I'll handle this once Ubuntu 24.04 has landed GS 46.
ATM all is stuck with time_t transition.

**Comment by prurigro** [comment]
If you hover over the app menu and see the border of the container, 8px puts about an even amount of space on both sides of the icon though it might be like 1px more... What do you think of 7?

**Comment by prurigro** [comment]
Ahh, matching the original spacing makes sense- I'd upgraded both my machines at once and didn't have a reference. Good call!

**Comment by fthx** [comment]
Sorry I remembered this PR after changing actor to child...

**Comment by fthx** [comment]
I now read the other points here.

**Comment by fthx** [comment]
What's the issue with spacing here?
image

**Comment by fthx** [comment]
I did not include the css.

**Comment by fthx** [comment]
Let's close this for now. If there is a spacing issue for you, please open a bug report.
It's uploaded to GS website now.

**Pull request closed without merging**
